//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicCare
{
    public partial class BookAppointment
    {
        /// <summary>pnlMessage control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>litMessage control.</summary>
        protected global::System.Web.UI.WebControls.Literal litMessage;

        /// <summary>vsBooking control.</summary>
        protected global::System.Web.UI.WebControls.ValidationSummary vsBooking;

        /// <summary>rfvFullName control.</summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFullName;

        /// <summary>rfvPhone control.</summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPhone;

        /// <summary>revPhone control.</summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revPhone;

        /// <summary>revEmail control.</summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;

        /// <summary>revNationalID control.</summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revNationalID;

        /// <summary>rfvSpecialty control.</summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvSpecialty;

        /// <summary>rfvDoctor control.</summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDoctor;

        /// <summary>rfvDate control.</summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDate;

        /// <summary>rvDate control.</summary>
        protected global::System.Web.UI.WebControls.RangeValidator rvDate;

        /// <summary>cvTimeSlot control.</summary>
        protected global::System.Web.UI.WebControls.CustomValidator cvTimeSlot;

        /// <summary>txtFullName control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        /// <summary>txtPhone control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        /// <summary>txtEmail control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>txtNationalID control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNationalID;

        /// <summary>rblGender control.</summary>
        protected global::System.Web.UI.WebControls.RadioButtonList rblGender;

        /// <summary>rblVisitType control.</summary>
        protected global::System.Web.UI.WebControls.RadioButtonList rblVisitType;

        /// <summary>ddlSpecialty control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlSpecialty;

        /// <summary>ddlDoctor control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlDoctor;

        /// <summary>txtAppointmentDate control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtAppointmentDate;

        /// <summary>cblTimeSlots control.</summary>
        protected global::System.Web.UI.WebControls.CheckBoxList cblTimeSlots;

        /// <summary>cblSymptoms control.</summary>
        protected global::System.Web.UI.WebControls.CheckBoxList cblSymptoms;

        /// <summary>txtNotes control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNotes;

        /// <summary>btnBook control.</summary>
        protected global::System.Web.UI.WebControls.Button btnBook;

        /// <summary>btnReset control.</summary>
        protected global::System.Web.UI.WebControls.Button btnReset;

        /// <summary>pnlSummary control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSummary;

        /// <summary>litReference control.</summary>
        protected global::System.Web.UI.WebControls.Literal litReference;

        /// <summary>litSumName control.</summary>
        protected global::System.Web.UI.WebControls.Literal litSumName;

        /// <summary>litSumGender control.</summary>
        protected global::System.Web.UI.WebControls.Literal litSumGender;

        /// <summary>litSumPhone control.</summary>
        protected global::System.Web.UI.WebControls.Literal litSumPhone;

        /// <summary>litSumEmail control.</summary>
        protected global::System.Web.UI.WebControls.Literal litSumEmail;

        /// <summary>litSumSpecialty control.</summary>
        protected global::System.Web.UI.WebControls.Literal litSumSpecialty;

        /// <summary>litSumDoctor control.</summary>
        protected global::System.Web.UI.WebControls.Literal litSumDoctor;

        /// <summary>litSumDate control.</summary>
        protected global::System.Web.UI.WebControls.Literal litSumDate;

        /// <summary>litSumSlot control.</summary>
        protected global::System.Web.UI.WebControls.Literal litSumSlot;

        /// <summary>litSumVisitType control.</summary>
        protected global::System.Web.UI.WebControls.Literal litSumVisitType;

        /// <summary>litSumSymptoms control.</summary>
        protected global::System.Web.UI.WebControls.Literal litSumSymptoms;

        /// <summary>litSumNotes control.</summary>
        protected global::System.Web.UI.WebControls.Literal litSumNotes;

        /// <summary>litSumStatus control.</summary>
        protected global::System.Web.UI.WebControls.Literal litSumStatus;
    }
}
