//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicCare
{
    public partial class Default
    {
        /// <summary>litDoctorCount control.</summary>
        protected global::System.Web.UI.WebControls.Literal litDoctorCount;

        /// <summary>litSpecialtyCount control.</summary>
        protected global::System.Web.UI.WebControls.Literal litSpecialtyCount;

        /// <summary>litPatientCount control.</summary>
        protected global::System.Web.UI.WebControls.Literal litPatientCount;
    }
}
