//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicCare
{
    public partial class Doctors
    {
        /// <summary>ddlFilterSpecialty control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterSpecialty;

        /// <summary>rptDoctors control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptDoctors;

        /// <summary>pnlNoDoctors control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoDoctors;
    }
}
