//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicCare
{
    public partial class Login
    {
        /// <summary>pnlMessage control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>litMessage control.</summary>
        protected global::System.Web.UI.WebControls.Literal litMessage;

        /// <summary>ctlLogin control.</summary>
        protected global::System.Web.UI.WebControls.Login ctlLogin;
    }
}
