//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicCare
{
    public partial class MyAppointments
    {
        /// <summary>txtLookup control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtLookup;

        /// <summary>btnLookup control.</summary>
        protected global::System.Web.UI.WebControls.Button btnLookup;

        /// <summary>pnlMessage control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>litMessage control.</summary>
        protected global::System.Web.UI.WebControls.Literal litMessage;

        /// <summary>pnlResults control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlResults;

        /// <summary>gvMyAppointments control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvMyAppointments;
    }
}
