//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicCare
{
    public partial class Register
    {
        /// <summary>pnlMessage control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>litMessage control.</summary>
        protected global::System.Web.UI.WebControls.Literal litMessage;

        /// <summary>ctlCreateUser control.</summary>
        protected global::System.Web.UI.WebControls.CreateUserWizard ctlCreateUser;
    }
}
