//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicCare
{
    public partial class SiteMaster
    {
        /// <summary>head control.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;

        /// <summary>frmMain control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm frmMain;

        /// <summary>phAdminMenu control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phAdminMenu;

        /// <summary>phAnonymous control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phAnonymous;

        /// <summary>phAuthenticated control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phAuthenticated;

        /// <summary>litUserName control.</summary>
        protected global::System.Web.UI.WebControls.Literal litUserName;

        /// <summary>litUserRoles control.</summary>
        protected global::System.Web.UI.WebControls.Literal litUserRoles;

        /// <summary>lnkSignOut control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkSignOut;

        /// <summary>MainContent control.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        /// <summary>litClinicName control.</summary>
        protected global::System.Web.UI.WebControls.Literal litClinicName;

        /// <summary>litClinicPhone control.</summary>
        protected global::System.Web.UI.WebControls.Literal litClinicPhone;

        /// <summary>litYear control.</summary>
        protected global::System.Web.UI.WebControls.Literal litYear;
    }
}
