//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicCare.Admin
{
    public partial class Backup
    {
        /// <summary>pnlMessage control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>litMessage control.</summary>
        protected global::System.Web.UI.WebControls.Literal litMessage;

        /// <summary>txtBackupFolder control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtBackupFolder;

        /// <summary>btnBackupNow control.</summary>
        protected global::System.Web.UI.WebControls.Button btnBackupNow;

        /// <summary>btnRefresh control.</summary>
        protected global::System.Web.UI.WebControls.Button btnRefresh;

        /// <summary>gvBackups control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvBackups;
    }
}
