//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicCare.Admin
{
    public partial class Dashboard
    {
        /// <summary>litTotalPatients control.</summary>
        protected global::System.Web.UI.WebControls.Literal litTotalPatients;

        /// <summary>litActiveDoctors control.</summary>
        protected global::System.Web.UI.WebControls.Literal litActiveDoctors;

        /// <summary>litTotalAppointments control.</summary>
        protected global::System.Web.UI.WebControls.Literal litTotalAppointments;

        /// <summary>litTodaysAppointments control.</summary>
        protected global::System.Web.UI.WebControls.Literal litTodaysAppointments;

        /// <summary>litPending control.</summary>
        protected global::System.Web.UI.WebControls.Literal litPending;

        /// <summary>litConfirmed control.</summary>
        protected global::System.Web.UI.WebControls.Literal litConfirmed;

        /// <summary>btnExportExcel control.</summary>
        protected global::System.Web.UI.WebControls.Button btnExportExcel;

        /// <summary>btnExportWord control.</summary>
        protected global::System.Web.UI.WebControls.Button btnExportWord;

        /// <summary>btnExportPdf control.</summary>
        protected global::System.Web.UI.WebControls.Button btnExportPdf;

        /// <summary>litExportCount control.</summary>
        protected global::System.Web.UI.WebControls.Literal litExportCount;

        /// <summary>gvToday control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvToday;
    }
}
