//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicCare.Admin
{
    public partial class ManagePatients
    {
        /// <summary>pnlMessage control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>litMessage control.</summary>
        protected global::System.Web.UI.WebControls.Literal litMessage;

        /// <summary>vsPatient control.</summary>
        protected global::System.Web.UI.WebControls.ValidationSummary vsPatient;

        /// <summary>rfvFullName control.</summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFullName;

        /// <summary>rfvPhone control.</summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPhone;

        /// <summary>revPhone control.</summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revPhone;

        /// <summary>revEmail control.</summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;

        /// <summary>revNationalID control.</summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revNationalID;

        /// <summary>litFormTitle control.</summary>
        protected global::System.Web.UI.WebControls.Literal litFormTitle;

        /// <summary>hfPatientID control.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hfPatientID;

        /// <summary>txtFullName control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        /// <summary>rblGender control.</summary>
        protected global::System.Web.UI.WebControls.RadioButtonList rblGender;

        /// <summary>txtDateOfBirth control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtDateOfBirth;

        /// <summary>txtPhone control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        /// <summary>txtEmail control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>txtNationalID control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNationalID;

        /// <summary>txtNotes control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNotes;

        /// <summary>btnSave control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>btnCancelEdit control.</summary>
        protected global::System.Web.UI.WebControls.Button btnCancelEdit;

        /// <summary>txtSearch control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>btnSearch control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>btnClearSearch control.</summary>
        protected global::System.Web.UI.WebControls.Button btnClearSearch;

        /// <summary>gvPatients control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvPatients;
    }
}
