//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicCare.Admin
{
    public partial class ManageDoctors
    {
        /// <summary>pnlMessage control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>litMessage control.</summary>
        protected global::System.Web.UI.WebControls.Literal litMessage;

        /// <summary>vsDoctor control.</summary>
        protected global::System.Web.UI.WebControls.ValidationSummary vsDoctor;

        /// <summary>rfvFullName control.</summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFullName;

        /// <summary>rfvSpecialty control.</summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvSpecialty;

        /// <summary>revEmail control.</summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;

        /// <summary>revPhone control.</summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revPhone;

        /// <summary>litFormTitle control.</summary>
        protected global::System.Web.UI.WebControls.Literal litFormTitle;

        /// <summary>hfDoctorID control.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hfDoctorID;

        /// <summary>txtFullName control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        /// <summary>ddlSpecialty control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlSpecialty;

        /// <summary>txtEmail control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>txtPhone control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        /// <summary>txtBio control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtBio;

        /// <summary>txtPhotoUrl control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhotoUrl;

        /// <summary>chkIsActive control.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkIsActive;

        /// <summary>btnSave control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>btnCancelEdit control.</summary>
        protected global::System.Web.UI.WebControls.Button btnCancelEdit;

        /// <summary>gvDoctors control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvDoctors;
    }
}
