//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicCare.Admin
{
    public partial class ManageAppointments
    {
        /// <summary>pnlMessage control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>litMessage control.</summary>
        protected global::System.Web.UI.WebControls.Literal litMessage;

        /// <summary>ddlFilterStatus control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterStatus;

        /// <summary>gvAppointments control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvAppointments;
    }
}
